### ISSUE TITLE
Process a feedback

### ISSUE THREAD

**Issue by petrkucerak** [petrkucerak/cestapustem#20]
# ToDo

- [x] odebrat odkaz na pisnicku
- [x] odebrat pisnicku z formulare
- [x] zmenit par slov na vek a bydliste
- [x] pridat Christus Vivit
